### ISSUE TITLE
Date sorting is not working in supervisor-summerize

### ISSUE THREAD

**Issue by nohelix** [nohelix/Behavior-autoanalysis#15]
Example: GP4

Task (Filter) | Detail (Filter) |   |  
-- | -- | -- | --
Reset |   | 01/04/2023 | 2
Rxn |   | 01/30/2023 | 9
TH |   | 01/27/2023 | 7
Training |   | 01/31/2023 | 3
  |   |   |  
  |   | Date | Filename
Reset | None | Overall | Averages
Rxn | Alone | Overall | Averages
TH | Alone | Overall | Averages
Training | Alone | Overall | Averages
TH | Alone | 12/21/2022 | 16kHz_15-75dB_50ms_8s
Training | Alone | 01/31/2023 | 8kHz_30-90dB_50ms_8s
Rxn | Alone | 01/30/2023 | 32kHz_30-90dB_50ms_8s
Rxn | Alone | 01/28/2023 | 32kHz_30-90dB_50ms_8s

**Comment by tofof** [comment]
There is very little that can be done about this as it's a consequence of the date strings being strings, not dates.

**Comment by tofof** [comment]
We might be able to manually examine the contents of the table that gets appended together and resort the rows using our own sorting function that interprets dates correctly, but sorting within Excel would still be broken.
