### ISSUE TITLE
Supervisor summerize getting missmatched number of columns

### ISSUE THREAD

**Issue by nohelix** [nohelix/Behavior-autoanalysis#25]
Issue is occurring for Rat_ID 181 & 182

df_table is 30 columns, df_blank, df_counts, and df_key are 29 columns

Its analysis_type = "Tone (Single)" so I don't know what the heck.

I have backed up the run_archive, rat_archive, and supervisor-summarize on Z:/

**Comment by nohelix** [comment]
Failure due to line 688
r[, (length(r) + 1):29] = NA # add columns to reach 29

**Comment by tofof** [comment]
closed by #[e2e59d5](https://github.com/nohelix/Behavior-autoanalysis/commit/e2e59d5d0239ff5d00219a68ba6156552a9c350d)
